src/LRSimulator/Models/Card.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LRSimulator.Models
{
    public class Card
    {
        public string id { get; set; }
        public string name { get; set; }
        public List<string> names { get; set; }
        public string manaCost { get; set; }
        public int cmc { get; set; }
        public List<string> colors { get; set; }
        public string type { get; set; }
        public List<string> supertypes { get; set; }
        public List<string> types { get; set; }
        public List<string> subtypes { get; set; }
        public string rarity { get; set; }
        public string set { get; set; }
        public string setName { get; set; }
        public string text { get; set; }
        public string artist { get; set; }
        public string number { get; set; }
        public string power { get; set; }
        public string toughness { get; set; }
        public string layout { get; set; }
        public string imageUrl { get; set; }
        public int? multiverseid { get; set; }
    }

    public class CardComparer : IComparer<string>
    {
        public int Compare(string s1, string s2)
        {
            if (IsNumeric(s1) && IsNumeric(s2))
            {
                if (Convert.ToInt32(s1) > Convert.ToInt32(s2)) return 1;
                if (Convert.ToInt32(s1) < Convert.ToInt32(s2)) return -1;
                if (Convert.ToInt32(s1) == Convert.ToInt32(s2)) return 0;
            }

            if (IsNumeric(s1) && !IsNumeric(s2))
                return -1;

            if (!IsNumeric(s1) && IsNumeric(s2))
                return 1;

            return string.Compare(s1, s2, true);
        }

        private bool IsNumeric(object value)
        {
            try
            {
                int i = Convert.ToInt32(value.ToString());
                return true;
            }
            catch
            {
                return false;
            }
        }
    }
}

src/LRSimulator/Models/Set.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LRSimulator.Models
{
    public class Set
    {
        public string name { get; set; }
        public string code { get; set; }
        public string releaseDate { get; set; }

        public int? LRReviewID { get; set; }
    }
}

src/LRSimulator/ViewModels/CardViewModel.cs
using LRSimulator.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LRSimulator.ViewModels
{
    public class CardViewModel
    {
        public Card Card { get; set; }
        public Grade Grade { get; set; }
    }
}

src/LRSimulator/ViewModels/SetViewModel.cs
using LRSimulator.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LRSimulator.ViewModels
{
    public class SetViewModel
    {
        public Set Set { get; set; }
        public List<Card> Cards { get; set; }
        public Dictionary<string, bool> RarityFilter { get; set; }
        public Dictionary<string, bool> ColorFilter { get; set; }
        public CardListViewModel UserGrades { get; set; }
    }
}

src/LRSimulator/Controllers/SetController.cs
using LRSimulator.DAL;
using LRSimulator.Models;
using LRSimulator.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace LRSimulator.Controllers
{
    public class SetController : Controller
    {
        private ApplicationDbContext db;

        public SetController(ApplicationDbContext context)
        {
            db = context;
        }

        public IActionResult Index(string id = "")
        {
            var set = new Set();
            var cards = new List<Card>();

            if (id == "KLD" || id == "kld")
            {
                set = new Set()
                {
                    name = "Kaladesh",
                    code = "KLD",
                    releaseDate = "2016-09-30"
                };

                using (StreamReader r = System.IO.File.OpenText(@"wwwroot/js/KLD.json"))
                {
                    string json = r.ReadToEnd();
                    var cardDTO = JsonConvert.DeserializeObject<CardDTO>(json);
                    cards = cardDTO.Cards;
                }
            }
            else
            {
                set = MTGAPI.GetSetBySetCode(id);
                cards = MTGAPI.GetCardsBySetCode(id);
            }

            var lrSetReviewQuery = db.SetReviews
                .Where(sr => sr.SetCode.Equals(id, StringComparison.OrdinalIgnoreCase))
                .FirstOrDefault();

            var lrSetReview = (lrSetReviewQuery == null) ? new List<Grade>() : lrSetReviewQuery.Grades;
            
            var rarityFilter = new Dictionary<string, bool>() {
                { "Common", false },
                { "Uncommon", false },
                { "Rare", false },
                { "Mythic Rare", false },
            };

            var colorFilter = new Dictionary<string, bool>() {
                { "White",  false },
                { "Blue", false },
                { "Black", false },
                { "Red", false },
                { "Green", false },
                { "Colorless", false }
            };

            cards = cards
                .Where(c => !c.type.Contains("Basic Land"))
                .OrderBy(c => c.number, new CardComparer())
                .ToList();

            var userGrades = new CardListViewModel();
            foreach (var card in cards)
            {
                var cvm = new CardViewModel()
                {
                    Card = card,
                    Grade = new Grade()
                    {
                        CardName = card.name,
                        MultiverseID = card.multiverseid ?? -1,
                        Value = GradeEnum.None
                    }
                };

                userGrades.CardViewModels.Add(cvm);
            }

            return View(new SetViewModel()
            {
                RarityFilter = rarityFilter,
                ColorFilter = colorFilter,
                Set = set,
                Cards = cards,
                UserGrades = userGrades
            });
        }

        [HttpPost]
        public IActionResult Index(SetViewModel model)
        {
            try
            {
                var setCode = model.Set.code;
                var cards = new List<Card>();

                if (setCode == "KLD" || setCode == "kld")
                {
                    using (StreamReader r = System.IO.File.OpenText(@"wwwroot/js/KLD.json"))
                    {
                        string json = r.ReadToEnd();
                        var cardDTO = JsonConvert.DeserializeObject<CardDTO>(json);
                        cards = cardDTO.Cards;
                    }
                }
                else
                {
                    cards = MTGAPI.GetCardsBySetCode(setCode);
                }

                var rarityFilter = model.RarityFilter;
                var colorFilter = model.ColorFilter;

                var rarityPredicate = GetRarityFilter(rarityFilter);
                var colorPredicate = GetColorFilter(colorFilter);

                cards = cards
                    .Where(c => !c.type.Contains("Basic Land"))
                    .Where(rarityPredicate)
                    .Where(colorPredicate)
                    .OrderBy(c => c.number, new CardComparer())
                    .ToList();

                var userGrades = new CardListViewModel();
                foreach (var card in cards)
                {
                    var cvm = new CardViewModel()
                    {
                        Card = card,
                        Grade = new Grade()
                        {
                            CardName = card.name,
                            MultiverseID = card.multiverseid ?? -1,
                            Value = GradeEnum.None
                        }
                    };

                    userGrades.CardViewModels.Add(cvm);
                }

                return PartialView("EditorTemplates/CardListViewModel", userGrades);
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", model.Set.code);
            }
        }

        [HttpPost]
        public IActionResult Export(List<CardViewModel> model)
        {
            return View();
        }

        private Func<Card, bool> GetColorFilter(Dictionary<string, bool> filter)
        {
            Func<Card, bool> predicate = card => true;

            if (filter.Any(r => r.Value))
                predicate = card => false;

            foreach (var color in filter)
            {
                if (color.Value)
                {
                    var copy = predicate;

                    if (color.Key == "Colorless")
                        predicate = card => copy(card) || (card.colors == null);
                    else
                        predicate = card => copy(card) || (card.colors != null && card.colors.Contains(color.Key));
                }
            }

            return predicate;
        }

        private Func<Card, bool> GetRarityFilter(Dictionary<string, bool> filter)
        {
            Func<Card, bool> predicate = card => true;

            if (filter.Any(r => r.Value))
                predicate = card => false;

            foreach (var rarity in filter)
            {
                if (rarity.Value)
                {
                    var copy = predicate;
                    predicate = card => copy(card) || card.rarity == rarity.Key;
                }
            }

            return predicate;
        }
    }
}

src/LRSimulator/Views/Set/Cards.cshtml
@using LRSimulator.Models;
@using LRSimulator.ViewModels;
@using LRSimulator.Utilities;
@using System.Linq;

@model List<CardRating>


@using (Html.BeginForm("Export", "Set"))
{
    <button type="submit" class="btn btn-default">Export</button>    

    <ul class="list-inline card-list">
        @for (var i = 0; i < Model.Count; i++)
        {
            <li>
                <div class="row">
                    <div class="col-xs-12">
                        <img src="@Model[i].Card.imageUrl" width="220" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-8">
                        <select class="form-control" asp-for="@Model[i].Grade.Value" asp-items="Html.GetEnumSelectList<GradeEnum>()"></select>
                        @*@Html.DropDownListFor(c => Model[i].Grade.Value, Html.GetEnumSelectList<GradeEnum>(), htmlAttributes: new { @class = "form-control" })*@
                    </div>
                </div>

            </li>
        }

        @*@foreach (var cardRating in Model)
        {
            <li>
                <div class="row">
                    <div class="col-xs-12">
                        <img src="@cardRating.Card.imageUrl" width="220" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-8">
                        <select class="form-control" asp-for="@cardRating.Grade.Value" asp-items="Html.GetEnumSelectList<GradeEnum>()"></select>
                    </div>
                </div>
            
            </li>
        }*@
    </ul>
    <button type="submit" class="btn btn-default">Export</button>
}

src/LRSimulator/Views/Set/Index.cshtml
@using LRSimulator.Models;
@model LRSimulator.ViewModels.SetViewModel

@{
    ViewData["Title"] = Model.Set.name;
}

@section scripts {
    <script type="text/javascript">
        $(function(){

            $('#sidebar-filter').on('submit', function (e) {
                e.preventDefault();

                var form = $(this);
                var cardsContainer = $('#cards-container');

                $.ajax({
                    type: form.attr('method'),
                    url: form.attr('action'),
                    data: form.serialize(),
                    success: function (data) {
                        cardsContainer.html(data);
                    }
                });

            });

        });
    </script>
}

<h1><span class="ss ss-@Model.Set.code.ToLower()" style="margin-right: 10px;"></span>@ViewData["Title"]</h1>

<hr />

<div class="row">
    <div class="col-xs-2">
        <form asp-controller="Set" asp-action="Index" 
            data-ajax="true" 
            data-ajax-method="POST" 
            data-ajax-mode="replace"
            data-ajax-update="#cards-container">

            <h4>Filter by Color</h4>

            @foreach (var color in Model.ColorFilter)
            {
                <div class="checkbox">
                    <label>
                        @Html.CheckBoxFor(model => model.ColorFilter[color.Key])
                        @color.Key
                    </label>
                </div>
            }

            <h4>Filter by Rarity</h4>

            @foreach (var rarity in Model.RarityFilter)
            {
                <div class="checkbox">
                    <label>
                        @Html.CheckBoxFor(model => model.RarityFilter[rarity.Key])
                        @rarity.Key
                    </label>
                </div>
            }

            @Html.HiddenFor(model => model.Set.code)

            <button type="submit" class="btn btn-default">Apply</button>
        </form>

        @*@using (Html.BeginForm("Index", "Set", method: FormMethod.Post, htmlAttributes: new { @id = "sidebar-filter" }))
        {
            <h4>Filter by Color</h4>

            foreach (var color in Model.ColorFilter)
            {
                <div class="checkbox">
                    <label>
                        @Html.CheckBoxFor(model => model.ColorFilter[color.Key])
                        @color.Key
                    </label>
                </div>
            }

            <h4>Filter by Rarity</h4>

            foreach (var rarity in Model.RarityFilter)
            {
                <div class="checkbox">
                    <label>
                        @Html.CheckBoxFor(model => model.RarityFilter[rarity.Key])
                        @rarity.Key
                    </label>
                </div>
            }

            @Html.HiddenFor(model => model.Set.code)

            <button type="submit" class="btn btn-default">Apply</button>
        }*@
    </div>
    <div class="col-xs-10" id="cards-container">
        @*@await Html.PartialAsync("Cards", Model.UserGrades)*@
        @using (Html.BeginForm("Export", "Set"))
        {
            <button type="submit" class="btn btn-default">Export</button>
            @Html.EditorFor(model => model.UserGrades)
            <button type="submit" class="btn btn-default">Export</button>
        }
    </div>
</div>